# Generated by Django 5.2.6 on 2025-10-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=150)),
                ('rphone', models.IntegerField(max_length=150)),
                ('remail', models.CharField(max_length=150)),
                ('rstudentname', models.CharField(max_length=150)),
                ('rmessage', models.CharField(max_length=150)),
            ],
        ),
    ]
