# Generated by Django 5.2.6 on 2025-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationalapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=150)),
                ('cphone', models.IntegerField(max_length=150)),
                ('cemail', models.CharField(max_length=150)),
                ('cmessage', models.CharField(max_length=150)),
            ],
        ),
    ]
